/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uy_com_cvaucher_services_jni_CvaucherJni */

#ifndef _Included_uy_com_cvaucher_services_jni_CvaucherJni
#define _Included_uy_com_cvaucher_services_jni_CvaucherJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uy_com_cvaucher_services_jni_CvaucherJni
 * Method:    holaMundo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_uy_com_cvaucher_services_jni_CvaucherJni_holaMundo
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
