/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_omt_javah_JavaH */

#ifndef _Included_com_omt_javah_JavaH
#define _Included_com_omt_javah_JavaH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_omt_javah_JavaH
 * Method:    omtJavaH
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uy_com_cvaucher.services_jni_JavaH
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
